### ISSUE TITLE
Roadmap review

### ISSUE THREAD

**Issue by Bonnarel** [lmichel/TAP-annoter#1]
1 ) Pourquoi Roadmap en anglais ? Le stagiaire est français.

2 ) the Voltt framework : de qui s'agit-il ? je ne comprends pas ... Libairie de Greg ?

3 ) Pourquoi commencer par déployer le projet dans Eclipse ? A quelle étape on crée la base de données sous-jacente. 
4 ) il faut prévoir une phase de lecture des specs et de compréhension du contexte
5 ) je suis perdu entre les MILESTONES et les autres items principaux.*
6 ) ce qu'il y a entre MILESTONE 1 et MILESTONE 3 n'est-il pas itératif ?
7 ) c'est quoi les "model data" dans ton esprit ?
8 ) utiliser datamodel partout plutôt que model
9 ) choix d' "annotation scheme" tu penses essayer InstanceIntoVOT et les GROUPES et faire choisir ou tu penses à autre chose ?
10 ) Bon, bref, globalement je suis pas mal largué. Je vais essayer de le réécrire enb reprenant ce que j'ai compris

**Comment by lmichel** [comment]
1) J'ai tout mis en anglais car on est sur Github et qu'il faut laisser la porte ouverte à d'éventuels contributeurs.
2) Voltt == lib de Greg
3) Le creation de la premiere base fait partie du deploiement dans Eclipse.
4) effectivement: à ajouter
5) Les MILESTONE sont des étapes qui nécessitent une validation formelle sur laquelle on s'appuiera pour la suite
6) A discuter
7) un data model à l'envers :-)
8) ok
9) perso je pense à InstanceIntoVOT.... Ca ne tiendrait qu'à moi, on partirait direct la dessus, mais tu me semblais plus réservé.
10)

**Comment by loumir** [comment]
Bilan fin de stage . 
Le code produit par Joann est en java . 
Il est basé sur un treeWalker qui analyse l'arbre des classes Mango et invoque les appenders proposés par un fichier de config Json, fourni en entrée et  lié à une représentation en MANGO des classes présentes dans  collection de données .
il est invoqué par une fonction de vollt.
Il rajoute en entrée qu'une query response TAP, en VOTABLE,  le mapping XML correspondant aux éléments de cette VOTable.

**Comment by lmichel** [comment]
vue la durée c'est un très bon bilan
