### ISSUE TITLE
question to greg : comment récupérer en tr/ td / au lieu du binaire 

### ISSUE THREAD

**Issue by loumir** [lmichel/TAP-annoter#7]
apparemment tous sont ok pour questionner Greg

**Comment by lmichel** [comment]
juste pour voir si FB watch

**Comment by Bonnarel** [comment]
YES !!!
Le 17/06/2021 à 15:50, Laurent MICHEL a écrit :

**Comment by loumir** [comment]
réponse avec une option de  VOTABLEFormat dans le code.
