### ISSUE TITLE
Le code

### ISSUE THREAD

**Issue by JoannVetter** [lmichel/TAP-annoter#8]
J'ai commencé à essayer de coder la fonction product_mapper sur le modèle de ce qui avait été fait en python, mais le code ne fonctionne pas et c'est un peu compliqué à débuguer car rien ne s'affiche. J'ai tenté des print dans la console et tout ce que je sais c'est qu'on ne peut pas rentrer dans le try dans ProductMapper.buildAnnotations et je ne sais pas pourquoi.. De ce que j'ai vu dans la doc mon code devrait fonctionner mais à l'évidence ce n'est pas le cas. Si quelqu'un a une idée de pourquoi ça ne fonctionne pas je suis preneur

**Comment by lmichel** [comment]
Difficile de repondre comme cela.
Tu n'es pas obligé de reprendre exactement ce qui est fait en python, mais plutot le principe.
Tu dois disposer des choses suivantes:
- un magasin avec des blocs de mapping correspondants  à des paramètres individuels. Les référénces y sont remplacées par un pattern facilenent identifiable : @@@@@
- Une ressource de configuration pour la table que tu dois annoter: tu as des exemples dans product_config. Actuellement cette ressource est en JSON, mais ensuite elle pourrait etre dans une table du TAP schéma.

Partant de là, pour créer ton bloc XML tu n'as qu'à lire la config produit et pour chaque paramètre que tu y trouves, tu ajoutes le bloc de mapping correspondant en remplaçant les @@@@@ par les noms de colonnes indiqués dans la config .

**Comment by Bonnarel** [comment]
Bonjour à vous trois
Comment çà a évolué ce point ?
François
Le 17/06/2021 à 18:29, JoannVetter a écrit :

**Comment by JoannVetter** [comment]
J'avais bien saisi le fonctionnement mais je n'arrive pas à débugger mon soucis, il y a un problème au niveau du parser visiblement mais je ne comprend pas pourquoi

**Comment by lmichel** [comment]
je ne suis guere dispo cet AM

**Comment by loumir** [comment]
pouvons nous documenter ce code pour expliquer les étapes prévues dans l annotation et l ordre de lancement( invocation) des méthodes class*.appender . 
c'est important de tracer ce qui est envisagé pour le rapport de stage . 

c'est un travail pour lequel je peux participer, mardi 22 par exemple.

**Comment by Bonnarel** [comment]
Désolé d'être en retard, mais j'ai regardé un peu le code

Est-ce que dans productMapper on a vraiment besoin de stocker le wrietr 
buffer dans this.out ? c'est pas une copie qui se fait à ce moment là ? 
(pas sur de moi)

Dans la classe d'origine le WriterBuffer "out" est simplement passé en 
paramètre de writeResults à writeHeader.

Parce que quand tu dis qu'on ne passe pas dans le try, tu vois vraiment 
rien en System.out à l'intérieur ou bien c'est juste que out.write ne 
donne rien ?

est on sur d'écrire dans le bon buffer ?
Le 17/06/2021 à 18:29, JoannVetter a écrit :

**Comment by JoannVetter** [comment]
Le problème est régle à ce niveau la, je ferme le thread et j'en ouvrirais d'autre si besoin !
